GET http://localhost:3000/user/
###
POST http://localhost:3000/users
Content-Type: application/json

###
DELETE http://localhost:3000/users
###
PATCH  http://localhost:3000/users/
Content-Type: application/json
